name: Agent service

on:
  push:
    branches: [master, main]
    paths:
      - "agent/**"
      - ".github/workflows/agent-service-check.yml"
  pull_request:
    paths:
      - "agent/**"
      - ".github/workflows/agent-service-check.yml"

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 24.x
        uses: actions/setup-node@v4
        with:
          node-version: "24.x"
          cache: "npm"
          cache-dependency-path: agent/package-lock.json

      - name: Install dependencies
        working-directory: agent
        run: npm ci

      - name: Run type check
        working-directory: agent
        run: npm run types

      - name: Run lint
        working-directory: agent
        run: npm run format:ci

  publish:
    runs-on: ubuntu-latest
    needs: check
    if: github.ref == 'refs/heads/master'

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push multi-arch Docker image
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -t ghcr.io/${{ github.repository }}/agent:latest \
            --push \
            ./agent
